language: generic

cache:
    apt: true

matrix:
    include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
            - kalakris-cmake
    - env: CXX=g++-5 CC=gcc-5 CXXFLAGS=-std=c++14
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: *sources
    - env: CXX=g++-4.9 CC=gcc-4.9 CXXFLAGS=-std=c++14
      addons:
        apt:
          packages:
            - g++-4.9
            - cmake
          sources: *sources

script:
    - cd cpp11training
    - mkdir build && cd build
    - cmake ..
    - make
    - ./cpp11training

