language: generic

sudo: required

cache:
    apt: true

matrix:
    include:
    - env: CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-7
            - cmake
          sources: &sources
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
            - kalakris-cmake
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
            - kalakris-cmake
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
            - kalakris-cmake

script:
    - cd cpp11training
    - mkdir build && cd build
    - cmake ..
    - make
    - ./cpp11training

